#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

start_service() {
	local enabled
	config_load wolwrt
	config_get_bool enabled main enabled 1
	[ "$enabled" = 1 ] || return 0
	procd_open_instance
	procd_set_param command /usr/sbin/wolwrtd
	procd_set_param respawn
	procd_set_param file /etc/config/wolwrt
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger wolwrt
}
