include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI interface for WOLwrt
LUCI_DEPENDS:=+wolwrt
LUCI_PKGARCH:=all

PKG_VERSION:=0.1.0
PKG_LICENSE:=MIT
PKG_MAINTAINER:=JorikSmith

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
